name: Flutter Package

on:
  push:
    branches: ["main"]
    # tags:
    #   - "v*" # This triggers the publish job when a tag starting with 'v' (e.g., v1.0.0) is pushed
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    if: ${{ contains(github.event.head_commit.message, '[run-ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout the code from the repository

      # Configure Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      # Install dependencies in the 'packages/puki' folder
      - run: flutter pub get
        working-directory: packages/puki # Run inside the 'packages/puki' directory

      # Run tests and generate coverage
      - run: flutter test --coverage
        working-directory: packages/puki # Run tests inside the 'packages/puki' directory

      # Upload coverage to Codecov

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/puki/coverage/lcov.info # Path to the coverage file inside the 'puki' package


  # publish: soon
